## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    if not bld.env['ENABLE_EXAMPLES']:
        return;

    obj = bld.create_ns3_program('PSO-simulation',
                                 ['pso-mobility','point-to-point','core','applications','mobility','config-store','netanim'])
    obj.source = 'PSO-simulation.cc'
